### PR TITLE
remove nesting of portal-header and portal-top viewlets

### LINKED ISSUE #286: plone.portaltop and plone.portalheader viewlets situation
We have seen this many times in our projects and I was hit by this last week so I decided to report it.

In Plone's `main_template.pt` there is a viewlet manager in use called `plone.portaltop` and included directly there, see:
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/main_template.pt#L58

If you check its registration in this plone.app.layout package, you can check that, *by default* there is only one viewlet registered to appear there, the viewlet `portal.header` here:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L140

As you can see in that registration, that viewlet just includes another viewlet manager called `plone.portalheader`, see:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/portal_header.pt

And this viewlet manager is the one where some more default viewlets are registered into such as the [plone.searchbox](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L156) the [portal.anontools](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L164) the [portal.membertools](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L173) or [plone.logo](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L182). Even plone.app.multilingual registers the [language change viewlet in plone.portalheader](https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/browser/configure.zcml#L199)

The point here is that if you need to override the internals of any of those viewlets for some reason (in our case we need to almost always override the language change viewlet) you need to be very careful because the `view` attribute of the viewlet is not anymore the `view` that is being rendered but the `plone.portaltop` viewlet. I think that this happens because of the double indirection of the "viewlets are registered to be shown in a viewlet manger that is shown through a viewlet in another viewletmanager".

I haven't done any tests but I think this can be easily resolved removing the `plone.portaltop` viewlet manager from the `main_template.pt` and replacing it with the contents of the actual `portal_header.pt` and thus including the `plone.portalheader` viewlet manager there. And of course changing any other registration that might happen in Plone's codebase from `plone.portaltop` to `plone.portalheader`. 

I even think that it simplifies a bit Plone's main_template and viewlet story.

I can't recall any historical reason why we have this like this in Plone.

Any thoughts?

### PR DESCRIPTION
**Pull request by erral**
Fixes #286 

to be tested together with

https://github.com/plone/Products.CMFPlone/pull/3416
https://github.com/plone/plone.app.upgrade/pull/268

### CODE REVIEW

**Comment by Rudd-O** [comment]
https://github.com/plone/plone.app.layout/issues/286#issuecomment-1027454879

**Comment by agitator** [comment]
@erral ping me on discord, got some questions ;-)

**Comment by erral** [comment]
PRs in place and all green 🥳

**Review by Rudd-O — APPROVED** [review]

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
We need:
- an upgrade step for this one that moves the viewlets registered for IPortalTop to IPortalHeader.
- we need IPortatlTop to be removed/deprecated, maybe it should become a deprecated alias of IPortalHeader
- I would also add some notes here: https://github.com/plone/documentation/blob/6-dev/docs/backend/upgrading/v60.md

**Comment by ale-rt** [comment]
CC @plone/framework-team

**Comment by erral** [comment]
We are not removing IPortalTop so I don't see why we need to move viewlets from IPortalTop to IPortalHeader.

We are removing the double nesting of viewlets manager here, see:

https://github.com/plone/plone.app.layout/issues/286

https://github.com/plone/Products.CMFPlone/pull/3416
https://github.com/plone/plone.app.upgrade/pull/268

We discussed this week the approach and decided to leave IPortalTop there in case there are existing registrations in addons on other products.

@agitator @MrTango @iham

**Comment by ale-rt** [comment]
I see, sorry for the noise!

**Review by MrTango — APPROVED** [review]
LGTM

**Pull request merged**
