### PR TITLE
Add a surrounding div to the plone.analytics viewlet [2.8]

### LINKED ISSUE #157: Should we add an id to analytics viewlet rendering?
This would make it easier for Diazo themes implementations. Some solutions [suggested by the community](https://stackoverflow.com/questions/12940552/diazo-ignores-the-javascript-for-web-statistics/12949084) involves adding an id to the script tag, but this solution IMHO is too much error prone (specially because official docs like https://developers.google.com/analytics/devguides/collection/analyticsjs/ are literally copy and paste for users).

In a nutshell: this

https://github.com/plone/plone.app.layout/blob/34d7d071cc6d8d6e7eb00895f078d1eaef2ad1c4/plone/app/layout/analytics/view.py#L31

would become

```python
return '<div id="plone.analytics">{0}</div>'.format(site_settings.webstats_js)
```

We would make a PR for this really simple suggestion, but we stil can't have a contributor's agreement because of some internal legal issues.

I know everyone is into Plone 5, but if someone decides to implement it would be very nice to be backported to Plone 4 as well.

### PR DESCRIPTION
**Pull request by erral**
Fixes #157 for Plone 5.1

@laulaz @idgserpro

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by idgserpro** [comment]
It may sound overkill, but I'm missing a test checking for this implementation. A simple python test checking for `plone-analytics` in `browser.contents` would suffice.

**Comment by erral** [comment]
Test added.

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
This was already merged for Plone 5.2, we could do the same here, right? @jensens

**Comment by mauritsvanrees** [comment]
It is pretty late in the game to change the html structure in Plone 5.1. See my [comment just now](https://github.com/plone/plone.app.layout/pull/219#issuecomment-540417452) for Plone 4.3.
This PR gives a small but useful new feature, but it causes possible breakage as well.

I would like Plone 5.1 releases to become boring. ;-)

Does anyone want to argue in favour of merging this in 5.1?

**Comment by jensens** [comment]
I share the same fear here. For 5.2 I merged it already and think it is fine. 
But I would really like to hear more opinions from other developers for 5.1 and 4.3 below (I dont think there's any further 5.0.x planned. 

@esteele  @MrTango @davisagli @agitator @thet - Who else?

**Comment by mauritsvanrees** [comment]
The merge on master has caused an unforeseen problem, which has been fixed, but a problem still remains (which might be a problem caused by the fix, not by your original PR, I don't know). See issue #227.
As said above, I would like Plone 5.1 releases to become boring. This does not sound boring. Sorry, but I will close this PR as well.

**Pull request closed without merging**
