### PR TITLE
add a sorrounding div to the plone.analytics viewlet

### LINKED ISSUE #157: Should we add an id to analytics viewlet rendering?
This would make it easier for Diazo themes implementations. Some solutions [suggested by the community](https://stackoverflow.com/questions/12940552/diazo-ignores-the-javascript-for-web-statistics/12949084) involves adding an id to the script tag, but this solution IMHO is too much error prone (specially because official docs like https://developers.google.com/analytics/devguides/collection/analyticsjs/ are literally copy and paste for users).

In a nutshell: this

https://github.com/plone/plone.app.layout/blob/34d7d071cc6d8d6e7eb00895f078d1eaef2ad1c4/plone/app/layout/analytics/view.py#L31

would become

```python
return '<div id="plone.analytics">{0}</div>'.format(site_settings.webstats_js)
```

We would make a PR for this really simple suggestion, but we stil can't have a contributor's agreement because of some internal legal issues.

I know everyone is into Plone 5, but if someone decides to implement it would be very nice to be backported to Plone 4 as well.

### PR DESCRIPTION
**Pull request by erral**
Fixes #157 in Plone 5.2

@laulaz @idgserpro

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
i'd use another id, since it could contain other snippets as well

**Comment by idgserpro** [comment]
@agitator I think the id might be this, to matches the viewlet name:

https://github.com/plone/plone.app.layout/blob/10ac3e4e4b8931054d684d265820557cbedaef5e/plone/app/layout/analytics/configure.zcml#L6

**Comment by erral** [comment]
Yes, I kept the same id as the viewlet (replacing the dot with a dash).

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
