### PR TITLE
4.3.x -  Add template and view arguments support to IBodyClassAdapters

### PR DESCRIPTION
**Pull request by rodfersou**

### CODE REVIEW

**Comment by rodfersou** [comment]
https://jenkins.plone.org/job/pull-request-4.3/lastBuild/console

**Comment by rodfersou** [comment]
https://jenkins.plone.org/job/pull-request-4.3/lastBuild/console

**Comment by rodfersou** [comment]
@plone/framework-team could you please review this PR?

**Comment by rodfersou** [comment]
@mauritsvanrees okay, doing the extra branches.

About the confusing.. I just start the second branch after the first (because one need the other).  After merge the first branch, the confuse is gone (the first commit will disappear literally).

**Comment by mauritsvanrees** [comment]
I think everything is done here on all branches. Thanks a lot @rodfersou!

**Pull request merged**
