### PR TITLE
Do not render social metadata if you are a logged user.

### PR DESCRIPTION
**Pull request by bsuttor**
This will closed https://github.com/plone/plone.app.layout/issues/99

### CODE REVIEW

**Comment by davisagli** [comment]
Packages that are imported by Products.CMFPlone are not allowed to use plone.api, because it creates a circular dependency.

**Comment by mauritsvanrees** [comment]
You removed the `plone.api` dependency from `setup.py` but you still use it in the code. That should be changed. You can use `getMultiAdapter` to get `plone_portal_state` and use the `anonymous` method from there.

**Comment by mauritsvanrees** [comment]
This needs a change in `Products.CMFPlone` because one of the [social controlpanel robot tests](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/robot/test_controlpanel_social.robot) is failing due to this change. The existing test should be adapted (the logged in user should no longer see the social tags) and a new one added to show that the tags are visible for anonymous users.

For clarity, you can run this robot test file locally with this command:

```
bin/test --all -s Products.CMFPlone -t test_controlpanel_social.robot
```

**Comment by bsuttor** [comment]
I started a jenkins pull-request-5.1 job with the 2 PRs as parameters

**Comment by mauritsvanrees** [comment]
I don't see that Jenkins pull request.

**Comment by gforcada** [comment]
@bsuttor maybe you were not logged in and after filling the form, then you were but the job was not started (it happened to me quite a few times already 😓 )

**Comment by gforcada** [comment]
I hope the two pull requests you were mentioning are:
https://github.com/plone/plone.app.layout/pull/100
https://github.com/plone/Products.CMFPlone/pull/2005

I started a job for them: http://jenkins.plone.org/job/pull-request-5.1/

**Comment by bsuttor** [comment]
@gforcada thank you. Indeed, I'm not sure I was logged. You had good PR, it seems PAM is breaked, but I'm not able to reproduce this robot test failure on my computer, 
So I restart a jenkins job: http://jenkins.plone.org/job/pull-request-5.1/1512, and I was logged :)

**Comment by bsuttor** [comment]
I also have to add https://github.com/plone/plone.app.multilingual/pull/265 PR into parameters to fix PAM tests. And now it's green

**Comment by mauritsvanrees** [comment]
LGTM, thanks. I will merge both.

**Pull request merged**
