### PR TITLE
WIP: delete README.txt from analytics sub package

### PR DESCRIPTION
**Pull request by gforcada**
It had outdated information anyway.

**Question:** should the code on that package be moved to viewlets with all the other viewlets? Does not make much sense to have two locations with viewlets...

### CODE REVIEW

**Comment by thet** [comment]
There are also the ``links`` and ``nextprevious`` subpackages, which contain viewlets and could be merged into ``viewlets``.

Moving the code around is a breaking change... Not sure, if there is any persistence involved like with portlets, which will break the site.

Ideally much of the code, especially the global views, navigation and sitemap code should go into CMFPlone. But that's possibly something for Plone 6.
Possibly viewlets won't play a big role in Plone-future, when we focus on tiles.

**Comment by gforcada** [comment]
@thet good points, so let's just remove this file and don't move things around, would that be fine?

**Comment by jensens** [comment]
You can move stuff around when providing BBB imports and deprecation warnings, then its not a breaking change.

**Comment by jensens** [comment]
see #132

**Pull request merged**
