### PR TITLE
add some body tags to determine permission needed and roles needed to view

### PR DESCRIPTION
**Pull request by djay**
The goal is https://github.com/plone/Products.CMFPlone/issues/465, which is make it easy for a themer to theme the backend separate from the frontend while still using the toolbar.

I'm not sure the viewrole- ones are needed (or desired for security reasons). Maybe it should just say be restricted to viewrole-anonymous?

I think with this change a seperated theme could be as simple as 
<theme if="body.viewpermission-view,body.viewpermission-none,body.viewrole-anonymous" href="...">

Also, need some advice on the best way to implement this. Seems a bit hacky.

### CODE REVIEW

**Comment by djay** [comment]
@vangheem @jcerjak advice?

**Comment by vangheem** [comment]
Sorry, about to get on plane. If you only need to check a few permissions,
maybe you just use checkPermission against the context object for each
permission you care about?

**Comment by djay** [comment]
@tomgross I've removed the tags about roles required. Seems permission required for a view is normally enough to differentiate backend vs frontend.
@vangheem so you think instead of revealing all permissions needed it should just be a binary tag? It would make the diazo rules clearer if it was ```backend``` maybe?

I guess I was thinking that something that requires an additional permission could then be themed differently. Perhaps thats where the roles required tags I deleted might have been useful, where you could theme in elements specific to reviewers for example?

**Comment by vangheem** [comment]
Simple is often better. All these things related to permissions might be a bit difficult for themers to fully get.

I am a bit worried about revealing this data publicly. Is this something we should worry about at all?

**Comment by djay** [comment]
You have to have the permission to see it so its not revealing much. The
public would only see view-permission-view or view-permission-none

**Comment by djay** [comment]
@vangheem so based on the other thread you seem to be proposing I change it so you would add the following in your custom there.


```
  <!-- Import Barceloneta rules -->
  <xi:include href="++theme++barceloneta/backend.xml" />

  <rules css:if-content="body.frontend" css:if-content="#visual-portal-wrapper">
               <theme href="index.html" />
    ....
```

or should it be  ```css:if-not-content="body.backend"```?

**Comment by djay** [comment]
@vangheem @esteele I've updated it so you can use either the body.frontend or body.viewpermission-view tags. Is there anything else I have to do?

**Comment by vangheem** [comment]
Looks fine.

**Comment by vangheem** [comment]
Can you add a changelog please? Don't bother with a PR for it.

**Comment by vangheem** [comment]
Oops, this didn't have a test run attached with it. I'll watch jenkins and revert if there is a problem.

**Comment by mauritsvanrees** [comment]
It causes a test failure in plone.app.portlets:

http://jenkins.plone.org/job/plone-5.0-python-2.7/2442/testReport/junit/plone.app.portlets/tests/testViewName_rst/

**Comment by mauritsvanrees** [comment]
oh, I may see the problem, giving it a quick try now

**Comment by vangheem** [comment]
yes, "getattr(view, '__ac_permissions__')" should be "getattr(view, '__ac_permissions__', None)"

Want me to make the change?

**Comment by mauritsvanrees** [comment]
Done. c29e1cb4251e478797dfed4cd6a52e3e4f0916ff

**Comment by vangheem** [comment]
thank you.

**Pull request merged**
