### PR TITLE
get the title from the registry in case the navigation root is the portal object [Plone 5.2]

### LINKED ISSUE #317: portal state does not compute navigation root title correctly when the navigation root is the portal root
Plone portal title is saved in the configuration registry and not in the Portal object itself. When using navigation_root_title the title is computed from the title attribute in the Portal object and not from the registry.

PR to come.

### PR DESCRIPTION
**Pull request by erral**
Fixes #317 for branch 3.x

to be tested and merged with https://github.com/plone/Products.CMFPlone/pull/3588

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — COMMENTED** [review]
I have a little bit of a concern this may break titles on sites building upon the current  behavior, even if it is not perfect. I added additional reviewers here.

**Review by mauritsvanrees — APPROVED** [review]
For me, this is fine. My guess is that there are more people confused by the current differences (if anyone notices) than that there are people who rely on the different behavior.

**Pull request merged**
