### PR TITLE
Rework sitemap.xml.gz view to fix it for plone.app.multilingual [2.3.x]

### PR DESCRIPTION
**Pull request by djowett**
Tests still required, but this is a suggested fix for #91

### CODE REVIEW

**Comment by djowett** [comment]
@jensens it's a bugfix in my book (for #91), but I wasn't sure which labels should apply to issues and which to PRs.  Is there any division? Or can they all apply to both?

**Comment by jensens** [comment]
ok, then its a bug (fix) label. I think its obvious that a PR with label bug must be a fix for a bug.

**Comment by djowett** [comment]
@jensens it is - I just wasn't sure if you used these Labels for any special filtering, and didn't want to break things if so ;-)

For example now https://github.com/plone/plone.app.layout/labels/01%20type%3A%20bug makes it look like there are 4 bugs when there are really 3, (this one is a fix for 91  already listed)

Whatever you are happy with is great with me :-)

**Comment by jensens** [comment]
As the changelog verifier tells you: Please add a note to ``CHANGES.rst`` - the change log file. I just started the tests.

**Comment by djowett** [comment]
@jensens sure - will do.  I also need to add tests in plone.app.multilingual & am hoping for someone to add tests in LinguaPlone to make sure we don't break that!

**Comment by djowett** [comment]
@erral I would like to rebase this branch to remove my trial & error from history. Are you (as the only person who has pulled it) OK with that ?

**Comment by djowett** [comment]
The tests for PAM 2.x just passed, but we still need tests on PAM 1.x & LinguaPlone

Just had a think through the dependencies, I'd appreciate a few more eyes to review this, as I 
haven't taken on a fix with this many dependencies before (in Plone).

@erral @jensens @mauritsvanrees + any others you think should see this.

| Plone version | multilingual product branch | LinguaPlone | PAM | p.a.layout | sitemap Status |
|------------------|-----------------------------------|-----------------|--------|-------------|--------------------|
| Plone 4.3       | with LinguaPlone (master)  | master(*)     | n/a    | 2.3.15      | working           | 
|                      | with PAM 1.x                     | n/a              | 1.2.3  | 2.3.15      | working           |
|                      | with PAM 2.x                     | n/a              | 2.0.3  | 2.3.15      | broken             |
|                      | none                                 | n/a              | n/a     | 2.3.15      | working            |
| Plone 5.0 / 5.1 | with PAM 3.x / 4.x / master | n/a            | 4.0.1  | 2.6.1        | broken            |
|                      | none                                 | n/a              | n/a     | 2.6.1        | presumed OK  |


(*) No new release should be required for LinguaPlone unless we break something!

New releases are required for 
- [ ] plone.app.layout 2.3.15
- [ ] plone.app.multilingual 1.2.3
- [ ] plone.app.multilingual 2.0.3
- [ ] plone.app.layout 2.6.1
- [ ] plone.app.multilingual 4.0.1

Backports could conceivably be required at some point for PAM 3.x or plone.app.layout 2.5

Version pins
The main issue is not to break the currently working sitemap when plone.app.multilingual 1.x is installed. So 1.2.3 needs to require plone.app.layout 2.3.15
2.0.3 should also require  plone.app.layout 2.3.15
The pins for Plone 5 are not so clear to me, is pinning into plone.app.layout 2.6.x branch (rather than 2.5) likely to cause other issues?   Maybe @thet you could comment on that?

**Comment by erral** [comment]
:+1: for rebase

**Comment by djowett** [comment]
@erral rebase is done.  Can you try cherry-picking the tests from PAM 2.x to PAM 1.x?  Can you give any input on the LinguaPlone tests?

**Comment by erral** [comment]
When cherry-picking the tests, I realized that p.a.layout 2.3.x is intended only for Plone >= 4.3 since version 2.3.11:

https://pypi.python.org/pypi/plone.app.layout/2.3.11

**Comment by djowett** [comment]
Ah, great another dependency!  

But PAM 1.x works on Plone 4.3 doesn't it?
If so, then tests are still relevant in PAM 1.x

**Comment by erral** [comment]
Here is the PAM 1.x pull-request with the changes done in PAM 2.x and the backported tests

https://github.com/plone/plone.app.multilingual/pull/235

**Comment by djowett** [comment]
Update of the [above table](https://github.com/plone/plone.app.layout/pull/92#issuecomment-223049182)

| Plone version | multilingual product (& branch) | old sitemap Status | p.a.layout fix in | Test location | Test status |
| --- | --- | --- | --- | --- | --- |
| Plone 4.3 | none | working | 2.3.16 | p.a.layout | ? |
|  | LinguaPlone (master) | working | 2.3.16 | LinguaPlone | Passes |
|  | PAM (1.x) | working | 2.3.16 | PAM 1.x | ? |
|  | PAM (2.x) | broken | 2.3.16 | PAM 2.x | ? |
| Plone 5.0 / 5.1 | none | working | 2.5.22 | p.a.layout | ? |
|  | PAM (master) | broken | 2.5.22 | PAM master | ? |
| Plone 4.2 | none | working | n/a | n/a | Not broken, so ain't fixing |
|  | LinguaPlone (master) | working | n/a | n/a | Not broken, so ain't fixing |

New releases (and tests) are required for 
- [ ] plone.app.layout 2.3.16
- [ ] plone.app.layout 2.5.22 

with Pins to the new p.a.layouts in new releases for 
- [ ] plone.app.multilingual 2.0.x
- [ ] plone.app.multilingual 4.0.x

and tests (but no releases) that we haven't broken anything in
- [ ] LinguaPlone master
- [ ] plone.app.multilingual 1.2.x (vs Plone 4.3 & p.a.layout 2.3.16)

Ports could conceivably be required at some point for PAM 3.x or plone.app.layout 2.6

**Comment by djowett** [comment]
Given tests passing in related products. I figure this PR is now ready to merge.  Anyone happy to review and do so for me?

cc @jensens @erral @Rudd-O

**Comment by jensens** [comment]
lgtm - is there any action needed in master?

**Comment by djowett** [comment]
@jensens Yep there will be, (or should that be in 2.5.x branch?), but I need a merge and release here, so I can pin in p.a.m 2.x to fix the real problem. I'll juggle those balls first, then come back to the others. Ok?

**Comment by jensens** [comment]
perfect, thanks a lot!

**Comment by djowett** [comment]
Thanks @jensens who should I ping for a release?

Can I also ask you on whether I need to also fix in 2.5.x branch or master or both? PAM master seems still to be testing against 2.5.x, but could it move to 2.6.x one day?

Is 2.6.x just for Plone 5.1? Changes that you and thet made here mention some "Incompatibilities", but I'm not clear what it IS compatible with :-)
https://github.com/plone/plone.app.layout/blob/master/CHANGES.rst#260-2016-05-10

**Comment by jensens** [comment]
@djowett for releases we have the @plone/release-team :)

**Comment by jensens** [comment]
IMO its first enough to fix master branch. PAM master tests should run against p.a.layout master branch, since this is all in core now. This should be updated in PAM id needed.

 Fixing 1.5.x as well is then more or less just cherry picking.

**Comment by djowett** [comment]
Agreed on all points. Thanks for clarifying

**Comment by djowett** [comment]
@plone/release-team please can we have a release of plone.app.layout from the 2.3.x branch?

**Comment by mauritsvanrees** [comment]
Sure. I have released plone.app.layout 2.3.16.

**Pull request merged**
