### PR TITLE
Integrate Plone20200121 hotfix: prevent XSS in title.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Part of https://plone.org/security/hotfix/20200121/xss-in-the-title-field-on-plone-5-0-and-higher

Only needed on master.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I will test this together with https://github.com/plone/plone.app.content/pull/193
They can be merged separately, but they solve part of the same security issue.

**Comment by mauritsvanrees** [comment]
Jenkins has no space left on device. That is node 2, which I think is the single one that I can reach. Seems okay there now though. Let's try again.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
