### PR TITLE
Pull display_publication_date_in_byline value from the configuration registry

### PR DESCRIPTION
**Pull request by esteele**
See also:
* https://github.com/plone/plone.app.upgrade/pull/46
* https://github.com/plone/Products.CMFPlone/pull/865

Refs plone/Products.CMFPlone#346

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/252/

**Comment by tisto** [comment]
PR looks good. Can be merged after Jenkins job has finished.

**Comment by esteele** [comment]
For what it's worth, those failing plone.app.layout tests do pass when the CMFPlone branch is included.

**Comment by tisto** [comment]
I checked out all three pull requests locally and I get two test failures in plone.app.layout:

```
Failure in test test_pub_date (plone.app.layout.viewlets.tests.test_content.TestDocumentBylineViewletView)
Traceback (most recent call last):
  File "/Users/timo/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/timo/.buildout/eggs/plone.app.layout-2.5.10-py2.7.egg/plone/app/layout/viewlets/tests/test_content.py", line 110, in test_pub_date
    self.assertEqual(viewlet.pub_date(), DateTime(effective.ISO8601()))
  File "/Users/timo/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/timo/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != DateTime('2015/09/05 15:10:23 GMT+2')

    210/1450 (14.5%)/Users/timo/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/DirectoryView.py:493: UserWarning: DirectoryView classic_ecmascript refers to a non-existing path 'plonetheme.classic:skins/classic_ecmascript'
  (self.id, reg_key), UserWarning)
    216/1450 (14.9%)

Failure in test testAddDisplayPublicationDateInBylineProperty (plone.app.upgrade.v43.tests.TestMigrations_v4_3alpha1)
Traceback (most recent call last):
  File "/Users/timo/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/timo/workspace/plone/buildout.coredev-5.0/src/plone.app.upgrade/plone/app/upgrade/v43/tests.py", line 28, in testAddDisplayPublicationDateInBylineProperty
    False)
  File "/Users/timo/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/timo/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != False


  Ran 1450 tests with 2 failures, 0 errors, 1 skipped in 4 minutes 26.789 seconds.
```

**Comment by esteele** [comment]
Those failing tests are fixed now.

**Comment by vangheem** [comment]
@esteele some rebasing on other packages. Everything looks fine though. Merge when ready.

**Pull request merged**
