### PR TITLE
Remove the ``plone.navtree`` content provider

### LINKED ISSUE #188: Fix content provider abuse
The `plone.global_sections` viewlet (which is a content provider) uses since https://github.com/plone/Products.CMFPlone/issues/2516 is merged another contentprovider (`plone.navtree`) to render the navigation.

IMHO this is not necessary.

I would like to remove the `plone.navtree` as soon as possible.

### PR DESCRIPTION
**Pull request by ale-rt**
Remove the ``plone.navtree`` content provider that was introduced in the context of the Navigation PLIP (https://github.com/plone/Products.CMFPlone/issues/2516)
The logic has been moved to the viewlet that was invoking it.

Fixes #188

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
idea of the plip was to also make it possible to use the markup within a tile, therefore the content provider
no further opinion ;-)

**Comment by jensens** [comment]
We also can wrap viewlets in `plone.app.standardtiles`. This should already work b/c the viewlet name is the same as before.

**Pull request merged**
