### PR TITLE
Remove Chrome Frame from X-UA-Compatible HTTP header as it's deprecated

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@esteele @vangheem this one is easy; can you merge?

**Comment by vangheem** [comment]
FWIW, it's nice to have the tests run against this before asking to get it merged.

- go to http://jenkins.plone.org/
- click login
- click "Pull Request 5.0"
- click "Build with Parameters"
- put https://github.com/plone/plone.app.layout/pull/70 into the input
- click "build"

**Comment by hvelarde** [comment]
done it, regardless I think testing this change is completely useless:

http://jenkins.plone.org/job/pull-request-5.0/491/

build is broken and has nothing to do with this change; no feedback on page.

what's next?

**Comment by hvelarde** [comment]
now, I see: the PR was merged and the branch no longer exists; thanks!

**Comment by vangheem** [comment]
Yes, I know testing this is a bit silly that's why I merged it right way. I was just giving an FYI.

And in any case, with changes like this, you don't need someone to merge for you. If no one complains and it's simple, just merge. People are watching and will yell if there is something amiss. We can always revert.

**Pull request merged**
