### PR TITLE
PLIP#20256 Add social meta tags viewlet

### PR DESCRIPTION
**Pull request by vangheem**
@bloodbare what do you think? merge if you think this is okay. related to: https://github.com/plone/Products.CMFPlone/pull/370

### CODE REVIEW

**Comment by vangheem** [comment]
plip added: https://dev.plone.org/ticket/20256

**Comment by bogdangi** [comment]
@vangheem , I think that this implementation is not easy to customize and extend, e.g. ``go:type`` for always ``website`` but if you have an ``article`` or a ``video`` it always shows as a ``website``.
I suggest create more flexible implementation like https://github.com/collective/collective.opengraph.

**Comment by vangheem** [comment]
I wanted to re-use the syndication infrastructure and I just figured, if users wanted to customize per-content type more than that, they'd just use the normal way of customizing a viewlet for a context object.

Perhaps the viewlet can be split into methods that can be overridden so it'd be easier to customize parts of the metadata. I don't think I want to introduce another sort of adaptable concept just for metatags...

**Comment by bogdangi** [comment]
@vangheem , In your case actually it makes sense for each content we create a viewlet and do not add more complexity with adapters or something like that.

**Pull request merged**
