### PR TITLE
Correctly select tab in GlobalSectionsViewlet

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/483/

**Comment by chris2fr** [comment]
Hi,

This fix looks good. What would we need to incorporate it?

Christopher

**Comment by jensens** [comment]
Its already applied and part of Plone 5

**Comment by chris2fr** [comment]
Great! Any ETA for inclusion as hot fix or next release? Currently not in Unified Installer. Any pointers on different installation procedure?

**Comment by jensens** [comment]
its part of https://pypi.python.org/pypi/plone.app.layout/2.5.18 since 2.5.16 (see changelog entry "Fixed global sections tabs. Issue CMFPlone#1178. [tomgross]")

**Comment by chris2fr** [comment]
Thank you.
http://dist.plone.org/release/5.0/versions.cfg
at this point specifies 
plone.app.layout                      = 2.5.15
The fix would be to change versions.cfg to 2.5.18

**Comment by jensens** [comment]
I recommend to switch to latest bugfix release http://dist.plone.org/release/5.0.2/versions.cfg

**Pull request merged**
