### PR TITLE
Issue 86 - Fix base tag differs from actual URL

### LINKED ISSUE #86: Base tag differs from actual URL
This is a 12 year-old bug migrated from: https://dev.plone.org/ticket/2988

Just to keep it clear: the HTML `<base>` element specifies the base URL to use for all relative URLs contained within a document.

There are 3 different cases that need to be tested:
1. folderish item with no default page defined: base tag and URL are the same
2. folderish item with default page defined: base tag and URL must be the same (this is the actual issue here)
3. any other item: base tag and URL are the same

### PR DESCRIPTION
**Pull request by rodfersou**
closes #86

### CODE REVIEW

**Comment by gforcada** [comment]
@rodfersou if you want to test your changes to make sure that nothing breaks and at the same time speeding its review, you can start jenkins jobs yourself: http://jenkinsploneorg.readthedocs.org/en/latest/run-pull-request-jobs.html

**Comment by rodfersou** [comment]
@gforcada I know, just need to improve my test a little bit before this..

**Comment by rodfersou** [comment]
After this change I got 3 failures in ``Products.CMFPlone``, and 3 failures in ``plone.app.collection``.

It looks like the failures happen because the request used in the test don't have the variable ``ACTUAL_URL`` setted with right value.

**Comment by rodfersou** [comment]
@plone/framework-team can someone take a look at these PR please?

**Comment by seanupton** [comment]
I am not the best judge of this, but this seems a good incremental change with little risk (AFAICT).

It might benefit from a functional test via zope.testbrowser, lxml.html that verifies what actually gets output to the DOM, but I'm not sure that is absolutely necessary.

**Comment by rodfersou** [comment]
@jensens @hvelarde green

**Comment by rodfersou** [comment]
:clap:

**Pull request merged**
